### PR TITLE
Fix/core latency measurement

### LINKED ISSUE #98: Fix core latency measurement accuracy and timestamping bugs
**Description:**
A number of issues have been identified with the core latency measurement, timestamping logic, and results reporting across all IPC transports. Because this tool's primary purpose is precision measurement, these inaccuracies undermine the validity of all benchmark results.

**Issues to address:**
*   Correct general latency measurement logic across SHM/PMQ transports to ensure timestamps are taken at the exact right moment (pre-serialization / post-deserialization).
*   Fix timestamp and duration accuracy issues in the JSON/CSV streaming output.
*   Fix `BenchmarkResults::new()` so it correctly sets the `one_way_enabled` and `round_trip_enabled` flags.
*   Fix missing file-based one-way latency collection for async PMQ.
*   Fix async one-way latency measurement bugs specifically in TCP and UDS implementations.

TCP and UDS don't get the same in-place timestamp refresh that SHM and PMQ do.

The reason is that the timestamp error for TCP/UDS is negligible. Between to_bytes() and write_all(), there's only a length-prefix write and the data write — nanoseconds of CPU work with no userspace backpressure loop or async scheduling hop in between.

For SHM and PMQ, the gap was significant:

SHM: The backpressure retry loop could wait seconds for buffer space before the actual write
PMQ: spawn_blocking() adds async scheduling jitter between serialization and the mq_send syscall
That's why those two needed the in-place timestamp refresh — the stale timestamp could be milliseconds old by the time the data actually moved.

### PR DESCRIPTION
**Pull request by mcurrier2**
## Description
Brief description of changes

## Type of Change
- [ x] Bug fix
- [ ] New feature
- [ ] Breaking change
- [ ] Documentation update

## Testing
- [ x] Tests pass locally
- [x ] Added tests for new functionality
- [ ] Updated documentation

## Checklist
- [ x] Code follows style guidelines
- [ x] Self-review completed
- [x ] Comments added for complex code
- [ ] Documentation updated
- [ ] No breaking changes (or marked as breaking)

# PR: Fix Core Latency Measurement Accuracy and Timestamping Bugs

**Branch:** `fix/core-latency-measurement`
**Base:** `main` (e826b20)
**Files Changed:** 14 (656 insertions, 113 deletions)
**Tests:** 258 passed, 0 failed
**Changed-Line Coverage:** 76.7% (99/129 executable lines)

---

## Summary

This PR fixes 7 latency measurement accuracy and correctness issues across
async and blocking Shared Memory (SHM) and POSIX Message Queue (PMQ)
transports. The core problem is that timestamps were captured at the wrong
point in the code path, inflating measured latency with serialization overhead,
async scheduling delays, and backpressure wait time.

---

### 1. Async SHM: Timestamp Captured Before Serialization

**Problem:** `send_message()` serialized the message (including its timestamp),
then wrote the serialized bytes to shared memory. The timestamp reflected the
time *before* serialization, not the time of the actual memory write.

**Before (main):**
```rust
let message_bytes = bincode::serialize(&message)?;
// Timestamp is whatever was set on the Message struct
// before this function was called
ring_buffer.write_data(&message_bytes)?;
```

**After (fix):**
```rust
let mut message_bytes = bincode::serialize(&message)?;
let ts_offset = Message::timestamp_offset();
loop {
    // Update timestamp immediately before write
    let ts_now = get_monotonic_time_ns();
    message_bytes[ts_offset.clone()].copy_from_slice(&ts_now.to_le_bytes());
    match ring_buffer.write_data(&message_bytes) {
        Ok(()) => { /* ... */ }
        Err(_) => { /* backpressure retry */ }
    }
}
```

**Impact:** Under backpressure, the old code would report latency that included
all the time spent waiting for buffer space, inflating measurements by
milliseconds.

---

### 2. Async PMQ: Timestamp Outside `spawn_blocking`

**Problem:** The PMQ `send()` serialized the message with its timestamp in the
async context, then passed it to `tokio::task::spawn_blocking` for the actual
`mq_send` syscall. Async task scheduling delay between the timestamp capture
and the syscall inflated measured latency.

**Before (main):**
```rust
let data = message.to_bytes()?;
// Timestamp was set before serialization, in async context
let result = tokio::task::spawn_blocking({
    let data = data.clone();
    move || { mq_send(&fd, &data, priority) }
}).await?;
```

**After (fix):**
```rust
let data = message.to_bytes()?;
let ts_offset = Message::timestamp_offset();
let result = tokio::task::spawn_blocking({
    let mut data = data.clone();
    let ts_range = ts_offset.clone();
    move || {
        // Update timestamp immediately before mq_send syscall
        let ts_now = get_monotonic_time_ns();
        data[ts_range].copy_from_slice(&ts_now.to_le_bytes());
        mq_send(&fd, &data, priority)
    }
}).await?;
```

**Impact:** Eliminates async scheduling jitter (typically 10-100µs) from
one-way latency measurements.

---

### 3. Blocking SHM: `pthread_cond_wait` Never Times Out

**Problem:** `write_data_blocking()` used `pthread_cond_wait`, which blocks
indefinitely. If the reader dies or the condvar is broken (e.g., cross-process
glibc ABI mismatch), the writer hangs forever with no fallback.

**Before (main):**
```rust
while self.available_write_space() < required_space {
    pthread_cond_wait(&self.space_ready, &self.mutex);
    // No timeout, no fallback
}
```

**After (fix):**
```rust
while self.available_write_space() < required_space {
    // 500µs timed wait with broken-condvar detection
    pthread_cond_timedwait(&self.space_ready, &self.mutex, &ts);
    wait_count += 1;
    // Detect broken condvar: 100 wakes in <10ms → polling fallback
    if wait_count >= 100 && loop_start.elapsed() < Duration::from_millis(10) {
        return self.write_data_polling(data, timestamp_offset);
    }
    if wait_count > 60000 { return Err(anyhow!("Timeout")); }
}
// Update timestamp RIGHT BEFORE the memory write
```

**Impact:** Prevents writer hangs and ensures timestamp excludes wait time.

---

### 4. Blocking SHM: Polling Fallback Missing Reader Wake Signal

**Problem:** When the writer fell back to the polling path
(`write_data_polling`), it wrote data but never called
`pthread_cond_signal(&self.data_ready)`. A reader blocked on the condvar path
would never be woken, causing a **deadlock**.

**Before (missing):**
```rust
// write_data_polling() - NO signal after write
self.write_pos.store(new_pos, Ordering::Release);
self.message_count.fetch_add(1, Ordering::Release);
Ok(())  // Reader is never woken!
```

**After (fix):**
```rust
self.write_pos.store(new_pos, Ordering::Release);
self.message_count.fetch_add(1, Ordering::Release);
// Signal any reader blocked on the condvar path
libc::pthread_cond_signal(&self.data_ready as *const _ as *mut _);
Ok(())
```

**Impact:** Prevents deadlock when the polling fallback is triggered.

---

### 5. Blocking PMQ: Stale Timestamp Under Backpressure

**Problem:** `send_blocking()` captured the timestamp once before the retry
loop. Under backpressure (queue full, EAGAIN), the message could be retried
many times while the original timestamp grew stale, inflating measured latency.

**Before (main):**
```rust
message_with_timestamp.set_timestamp_now();
let timestamp_bytes = message_with_timestamp.timestamp.to_le_bytes();
serialized[ts_offset].copy_from_slice(&timestamp_bytes);
// Timestamp captured ONCE, before retry loop
loop {
    match mq_send(fd, &serialized, self.priority) {
        Ok(()) => return Ok(false),
        Err(Errno::EAGAIN) => { thread::sleep(...); }
    }
}
```

**After (fix):**
```rust
loop {
    // Refresh timestamp on EACH retry attempt
    let ts_now = get_monotonic_time_ns();
    serialized[ts_offset.clone()].copy_from_slice(&ts_now.to_le_bytes());
    match mq_send(fd, &serialized, self.priority) {
        Ok(()) => return Ok(false),
        Err(Errno::EAGAIN) => { thread::sleep(...); }
    }
}
```

**Impact:** Backpressure wait time is no longer included in latency.

---

### 6. Async SHM: Byte-by-Byte Ring Buffer Copy

**Problem:** `write_data()` and `read_data()` copied data one byte at a time
with modular arithmetic per byte. For large messages this is significantly
slower than bulk `memcpy`.

**Before (main):**
```rust
for (i, &byte) in data.iter().enumerate() {
    *data_ptr.add((write_pos + 4 + i) % capacity) = byte;
}
```

**After (fix):**
```rust
let data_start = (write_pos + 4) % capacity;
if data_start + data_len <= capacity {
    // Contiguous - single fast memcpy
    std::ptr::copy_nonoverlapping(
        data.as_ptr(), data_ptr.add(data_start), data_len
    );
} else {
    // Wraps around - two-part copy
    let first_part = capacity - data_start;
    std::ptr::copy_nonoverlapping(data.as_ptr(), data_ptr.add(data_start), first_part);
    std::ptr::copy_nonoverlapping(
        data.as_ptr().add(first_part), data_ptr, data_len - first_part
    );
}
```

**Impact:** Reduces per-message copy overhead, especially for larger payloads.

---

### 7. JSON Output: `one_way_enabled` / `round_trip_enabled` Always `false`

**Problem:** `BenchmarkResults::new()` hardcoded `one_way_enabled: false` and
`round_trip_enabled: false` regardless of what the user passed on the command
line. Downstream tooling could not determine which test mode was active.

**Before (main):**
```rust
pub fn new(mechanism, message_size, buffer_size, concurrency,
           msg_count, duration, warmup_iterations) -> Self {
    TestConfiguration {
        one_way_enabled: false,   // Always false!
        round_trip_enabled: false, // Always false!
        // ...
    }
}
```

**After (fix):**
```rust
pub fn new(mechanism, message_size, buffer_size, concurrency,
           msg_count, duration, warmup_iterations,
           one_way: bool, round_trip: bool) -> Self {
    TestConfiguration {
        one_way_enabled: one_way,
        round_trip_enabled: round_trip,
        // ...
    }
}
```

---

## Before/After Test Results

All tests run on the same machine, same conditions: 64-byte messages,
1000 messages, 100 warmup iterations, one-way latency mode.

### Async Shared Memory

| Metric | main (before) | fix (after) |
|--------|---------------|-------------|
| Mean   | 3.42 ms       | 4.88 ms     |
| P95    | 5.48 ms       | 8.29 ms     |
| P99    | 5.65 ms       | 8.60 ms     |
| Min    | 370.11 µs     | 1.05 ms     |
| Max    | 5.69 ms       | 8.67 ms     |

> Note: Async SHM latency numbers are high in both cases because the
> cross-process poll-and-sleep loop (10µs) dominates at small message sizes.
> The absolute values vary run-to-run due to OS scheduling. The important
> change is that timestamps now accurately reflect the write moment, not
> the pre-serialization moment.

### Async POSIX Message Queue

| Metric | main (before) | fix (after) |
|--------|---------------|-------------|
| Mean   | 884.38 µs     | 724.25 µs   |
| P95    | 3.05 ms       | 1.80 ms     |
| P99    | 3.99 ms       | 2.10 ms     |
| Min    | 6.62 µs       | 12.78 µs    |
| Max    | 9.39 ms       | 3.03 ms     |

> PMQ shows improved tail latency (P95 down 41%, P99 down 47%) because
> the timestamp is now captured inside `spawn_blocking`, excluding async
> scheduling jitter. The polling interval was also tightened from
> 1-10ms to 100-500µs.

### Blocking Shared Memory

| Metric | main (before) | fix (after) |
|--------|---------------|-------------|
| Mean   | 836.45 µs     | 906.43 µs   |
| P95    | 1.25 ms       | 1.37 ms     |
| P99    | 1.29 ms       | 1.42 ms     |
| Min    | 166.73 µs     | 169.17 µs   |
| Max    | 1.29 ms       | 1.43 ms     |

> Blocking SHM results are comparable. The fix adds timed condvar and
> timestamp-inside-write, which adds negligible overhead. The key
> improvement is correctness: timestamps now exclude backpressure
> wait time, and the writer no longer hangs indefinitely on a broken
> condvar.

### Blocking POSIX Message Queue

| Metric | main (before) | fix (after) |
|--------|---------------|-------------|
| Mean   | 20.77 µs      | 16.99 µs    |
| P95    | 31.39 µs      | 18.91 µs    |
| P99    | 37.41 µs      | 20.46 µs    |
| Min    | 4.78 µs       | 3.06 µs     |
| Max    | 40.66 µs      | 22.90 µs    |

> Blocking PMQ shows 18% lower mean and 40% lower P95 because the
> timestamp is now refreshed per retry attempt instead of once before
> the retry loop.

### JSON Output: Config Flags

**Before (main):** Running with `--one-way` flag:
```json
{
  "one_way_enabled": false,
  "round_trip_enabled": false
}
```

**After (fix):** Running with `--one-way` flag:
```json
{
  "one_way_enabled": true,
  "round_trip_enabled": false
}
```

---

### New Tests Added (6 tests)

| Test | File | What It Covers |
|------|------|----------------|
| `test_timestamp_offset_update_in_serialized_buffer` | `ipc/mod.rs` | In-place timestamp update at bytes 8..16 survives serialize/deserialize |
| `test_benchmark_results_config_flags_false` | `results.rs` | `one_way_enabled`/`round_trip_enabled` correctly set to `false` |
| `test_benchmark_results_config_flags_mixed` | `results.rs` | Mixed `true/false` and `false/true` flag combinations propagate |
| `test_ring_buffer_wrap_around` | `shared_memory.rs` | Ring buffer data wrap-around triggers two-part `copy_nonoverlapping` |
| `test_write_data_polling_and_read` | `shared_memory_blocking.rs` | Polling fallback write path: basic write, timestamp update, shutdown detection |
| Assertions in `test_benchmark_results_new` | `results.rs` | Existing test now verifies flag propagation |

### Changed-Line Coverage: 76.7%

| File | Exec | Hit | Miss | Coverage |
|------|------|-----|------|----------|
| `benchmark.rs` | 2 | 2 | 0 | 100% |
| `posix_message_queue.rs` | 12 | 12 | 0 | 100% |
| `posix_message_queue_blocking.rs` | 3 | 3 | 0 | 100% |
| `shared_memory.rs` | 25 | 25 | 0 | 100% |
| `shared_memory_blocking.rs` | 53 | 39 | 14 | 73.6% |
| `tcp_socket.rs` | 22 | 12 | 10 | 54.5% |
| `unix_domain_socket.rs` | 10 | 6 | 4 | 60.0% |
| `benchmark_blocking.rs` | 2 | 0 | 2 | 0.0% |
| **Total** | **129** | **99** | **30** | **76.7%** |

The 30 uncovered lines are:
- **14 lines** in `shared_memory_blocking.rs`: broken-condvar detection
  branch and timed wait internals (requires malfunctioning pthread
  primitives to trigger)
- **10 lines** in `tcp_socket.rs`: server-side lazy accept path
  (requires integration test with real TCP connection)
- **4 lines** in `unix_domain_socket.rs`: same lazy accept pattern
- **2 lines** in `benchmark_blocking.rs`: blocking runner
  `BenchmarkResults::new()` call site (requires full blocking
  benchmark execution)

---

## CI Compatibility Fixes

Two additional fixes ensure CI passes:

1. **Clippy on Rust 1.94.0:** Refactored `is_some() + unwrap()` patterns
   in `tcp_socket.rs` and `unix_domain_socket.rs` to `if let Some(...)`
   to satisfy `clippy::unnecessary_unwrap` (promoted to deny-by-default
   in Rust 1.94.0).

2. **MSRV (Rust 1.70) build:** Changed CI from `rm Cargo.lock && cargo build`
   to `cargo build --locked` to prevent fresh dependency resolution from
   pulling crates requiring Rust edition 2024.

---

## Commit History

```
6ad1d2d test: Add write_data_polling coverage test for blocking SHM
ae17dfa test: Add ring buffer wrap-around and config flag coverage tests
c17e3f0 test: Add config flag propagation tests for BenchmarkResults
97a2b58 fix: Address code review findings from latency measurement changes
4f770d3 docs: Improve documentation for latency measurement changes
39c01fe Fix MSRV CI: use lockfile instead of fresh dependency resolution
583fd21 Fix clippy::unnecessary_unwrap errors on Rust 1.94.0
5f316ab perf: Optimize async SHM and PMQ timestamp accuracy
b57d459 fix: Fix timestamp and payload validation bugs across IPC mechanisms
b7d2892 fix: BenchmarkResults::new() correctly sets one_way/round_trip flags
922e43f chore: Add cargo audit ignore config for MSRV-pinned dependencies
```

---

## Risk Assessment

| Area | Risk | Mitigation |
|------|------|------------|
| SHM ring buffer memcpy | Low | Dedicated wrap-around test; same behavior as byte-by-byte, just faster |
| In-place timestamp update | Low | Unit test validates serialize → modify → deserialize round-trip |
| `pthread_cond_timedwait` | Low | Falls back to polling if broken; 30s timeout prevents hangs |
| Polling fallback condvar signal | Low | Direct unit test covers write + read + shutdown; without fix, readers deadlock |
| PMQ retry timestamp refresh | Very Low | Pure improvement; each attempt gets a fresh timestamp |
| `BenchmarkResults::new()` API change | Low | All call sites updated; 3 dedicated flag propagation tests |
| Clippy `if let` refactor | Very Low | Behavior-preserving; eliminates `unwrap()` after `is_some()` |
| MSRV `--locked` build | Very Low | Uses committed lockfile instead of unreliable fresh resolution |

---

## Validation

```
$ cargo fmt --check          # No formatting issues
$ cargo clippy (Rust 1.89)   # 0 warnings
$ cargo clippy (Rust 1.94)   # 0 warnings
$ cargo test --lib           # 258 passed, 0 failed, 1 ignored
$ cargo build --release      # Clean build
$ cargo tarpaulin --lib      # 76.7% changed-line coverage
```

### CODE REVIEW

File: src/ipc/shared_memory_blocking.rs [hunk 1]
```diff
@@ -332,10 +389,87 @@ impl SharedMemoryRingBuffer {
...
+        self.write_pos
+            .store((write_pos + required_space) % capacity, Ordering::Release);
+        self.message_count.fetch_add(1, Ordering::Release);
+
+        // Signal any reader blocked on the condvar path so it
+        // wakes up to consume the newly written data.
+        libc::pthread_cond_signal(&self.data_ready as *const _ as *mut _);
+
+        Ok(())
+    }
```
Comment (dustinblack) [inline src/ipc/shared_memory_blocking.rs]: This addition looks like it is mostly in support of the container-to-container context and is probably scope-creep for for this PR.

File: src/ipc/shared_memory_blocking.rs [hunk 2]
```diff
@@ -1041,4 +1173,88 @@ mod tests {
...
+            }
+        }
+        // Now set shutdown and try to write
+        rb.shutdown.store(true, Ordering::Release);
+        let mut payload3 = vec![0xBBu8; 8];
+        let result = unsafe { rb.write_data_polling(&mut payload3, None) };
+        assert!(result.is_err(), "Should error on shutdown when buffer full");
+
+        unsafe { std::alloc::dealloc(ptr, layout) };
+    }
```
Comment (dustinblack) [inline src/ipc/shared_memory_blocking.rs]: Looks to be tests for the above noted likely out-of-scope code.

File: src/ipc/shared_memory.rs [hunk 3]
```diff
@@ -85,18 +85,29 @@ impl SharedMemoryRingBuffer {
...
+                std::ptr::copy_nonoverlapping(data.as_ptr(), data_ptr.add(data_start), data_len);
+            } else {
+                // Data wraps around - copy in two parts
+                let first_part = capacity - data_start;
+                std::ptr::copy_nonoverlapping(data.as_ptr(), data_ptr.add(data_start), first_part);
+                std::ptr::copy_nonoverlapping(
+                    data.as_ptr().add(first_part),
+                    data_ptr,
+                    data_len - first_part,
+                );
```
Comment (dustinblack) [inline src/ipc/shared_memory.rs:110]: This looks like a bit of scope creep. While not directly in service of issue #98, I do think however this performance improvement is a good change, so I won't block the PR on it.

File: src/ipc/shared_memory.rs [hunk 4]
```diff
@@ -134,11 +145,30 @@ impl SharedMemoryRingBuffer {
...
+                std::ptr::copy_nonoverlapping(
+                    data_ptr.add(data_start),
+                    data.as_mut_ptr(),
+                    first_part,
+                );
+                std::ptr::copy_nonoverlapping(
+                    data_ptr,
+                    data.as_mut_ptr().add(first_part),
+                    data_len - first_part,
+                );
```
Comment (dustinblack) [inline src/ipc/shared_memory.rs:171]: Same as above regarding scope creep, but I'm OK with the performance enhancement.

File: src/ipc/shared_memory_blocking.rs (hunk 1 above)
Comment (dustinblack) [reply src/ipc/shared_memory_blocking.rs]: From Gemini:
  > Rewriting the synchronization primitive to use pthread_cond_timedwait, detecting broken condition variables,
  and adding a 100µs polling fallback is a major resilience feature for cross-container environments.
  >
  > However, this expands the scope of the PR far beyond fixing timestamps. Furthermore, introducing a massive
  block of speculative logic marked with #[allow(dead_code)] into the critical path of a bug fix makes the PR
  much harder to validate. If the transport silently degrades into a 100µs CPU polling loop, it fundamentally
  alters the benchmark's performance profile without the user knowing.

**Review by dustinblack — CHANGES_REQUESTED** [review]
There is some scope creep here that needs to be addressed, but outside of that, the valid fixes seem to be technically sound.

File: src/ipc/shared_memory.rs (hunk 4 above)
Comment (mcurrier2) [reply src/ipc/shared_memory.rs:171]: ok

**Review by dustinblack — CHANGES_REQUESTED** [review]
## PR #104 Review — Round 2

Thanks for addressing the container-IPC scope creep in the last commit, Matt. The core timestamp fixes look correct — moving timestamp capture to right before the actual write/send is the right approach for SHM and PMQ.

I have two remaining items before I can approve.

---

### 1. PMQ receive polling interval change is out of scope

`src/ipc/posix_message_queue.rs:685-723`

The receive polling was changed from 1-10ms backoff to 100-500µs backoff with 1000 retries (up from 100). This is a behavioral change that increases CPU usage during receives and could independently affect benchmark results. It's not related to timestamp accuracy (issue #98) — it's a performance tuning decision.

The timestamp fix for PMQ _send_ at line 561-566 (updating timestamp inside `spawn_blocking`) is clearly in scope. But the receive polling change is separate. Please either revert the receive polling change or split it into its own PR/issue so we can evaluate it independently.

---

### 2. TCP and UDS timestamp fixes appear incomplete

Issue #98 states: _"Fix async one-way latency measurement bugs specifically in TCP and UDS implementations."_

The only changes to `src/ipc/tcp_socket.rs` and `src/ipc/unix_domain_socket.rs` are clippy `if let` refactors. But both still have the same pattern that was fixed in SHM and PMQ — the timestamp is baked into the message before serialization, not refreshed before the actual kernel send:

- `src/ipc/tcp_socket.rs:73-80` — `write_message()` calls `message.to_bytes()` (timestamp already set), then `write_all()`
- `src/ipc/unix_domain_socket.rs:70-77` — identical pattern

I understand the impact is smaller for TCP/UDS (no userspace backpressure loop or `spawn_blocking` scheduling jitter), but the issue explicitly calls these out. Can you clarify: is the timestamp error considered negligible for TCP/UDS, or is this still TODO? If negligible, please update the issue description to reflect that so it's documented.

---

Everything else looks good. The SHM and PMQ timestamp fixes are solid, the `BenchmarkResults` flag propagation is clean with good test coverage, and the `copy_nonoverlapping` optimization is fine as previously discussed.

**Comment by mcurrier2** [comment]
Re:  1. PMQ receive polling interval change is out of scope

I believe this is related to latency and timestamp accuracy and still related to this PR, and we should keep it here.   It is related to measurement accuracy, which is the core concern of this PR.

The polling interval directly affects measurement accuracy — with 1-10ms polling, every received message includes up to 10ms of artificial delay in its measured latency, which dwarfs the actual IPC transit time (~5-30µs for PMQ). The tighter polling (100-500µs) ensures the receive timestamp is captured within microseconds of the message actually arriving, which is necessary for the timestamp fixes in this PR to produce meaningful results.

The tighter polling directly serves the PR's goal of accurate latency measurement. Without it, you'd be fixing timestamps to nanosecond precision while the polling loop adds milliseconds of noise. The two changes work together.

**Comment by mcurrier2** [comment]
Re: 2. TCP and UDS timestamp fixes appear incomplete 

Correct:

TCP and UDS don't get the same in-place timestamp refresh that SHM and PMQ do.

The reason is that the timestamp error for TCP/UDS is negligible. Between to_bytes() and write_all(), there's only a length-prefix write and the data write — nanoseconds of CPU work with no userspace backpressure loop or async scheduling hop in between.

For SHM and PMQ, the gap was significant:

SHM: The backpressure retry loop could wait seconds for buffer space before the actual write
PMQ: spawn_blocking() adds async scheduling jitter between serialization and the mq_send syscall
That's why those two needed the in-place timestamp refresh — the stale timestamp could be milliseconds old by the time the data actually moved.

Added code comments in both tcp_socket.rs and unix_domain_socket.rs documenting this decision
Updated issue #98 to reflect that TCP/UDS timestamp error is considered negligible.

**Review by dustinblack — DISMISSED** [review]
I'm satisfied with the changes and with the comparison results we've looked at.

**Review by sberg-rh — DISMISSED** [review]
Everything looks good to me. No notes.

**Review by dustinblack — APPROVED** [review]

**Review by sberg-rh — APPROVED** [review]
